services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springtraining
    ports:
      - "3306:3306"
    networks:
      - akpsnetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  sprng-website-app:
    image: spring-website-selenium:latest
    container_name: spring-website-selenium-app
    depends_on:
      mysql_db:
        condition: service_healthy
    ports:
      - "7075:8080"
    networks:
      - akpsnetwork
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/springtraining
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

networks:
  akpsnetwork:
    external: true